### PR TITLE
Use Docker for travis tests

### PR DESCRIPTION
**Pull request by fredemmott**

### CODE REVIEW

**Comment by fredemmott** [comment]
Remaining failures look like they're probably environment assumptions in shipit/hg/git that need fixing

**Comment by sdwilsh** [comment]
It looks like it's installing a pretty old version of hg too, which maybe be some of the issue.

**Comment by fredemmott** [comment]
I don't think I'll be able to look at the remaining problems - hopefully this is a useful starting point.

**Comment by fredemmott** [comment]
If you have docker installed locally, you can debug this interactively with:

```
docker run -it -v $(pwd):/var/source hhvm/hhvm:3.21-lts-latest /bin/bash -l
```

Then, in the container, the entire repo (including .travis.sh) will be in `/var/source`

`-i` enables interactive mode, and `-t` gets you a tty.

**Comment by sdwilsh** [comment]
Where's the fun in that?  I got it working the hard way :P

**Pull request closed without merging**
