### PR TITLE
Don't use PCRE to strip file list from patch.

### PR DESCRIPTION
**Pull request by skevy**
Resolves comments in #13

### CODE REVIEW

**Comment by fredemmott** [comment]
@facebook-GitHub-bot import

**Comment by fredemmott** [comment]
@facebook-github-bot import

... wonder if it's case-sensitive :/

**Comment by fredemmott** [comment]
@facebook-github-bot import

**Comment by fredemmott** [comment]
Waiting for internal test runs, but this definitely fixes the problem, thanks :)

**Comment by skevy** [comment]
👍

**Comment by fredemmott** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
