### PR TITLE
Cleanup .travis.sh and fix TravisCI

### PR DESCRIPTION
**Pull request by bigfootjon**
* /bin/sh is not guaranteed to include `$()`, /bin/bash is
* Remove `composer.lock` to align with other hhvm projects
* `composer upgrade` can't install packages if `composer.lock` is missing, use `composer install` instead
* `vendor/**/tests` cause problems when composer clones dependencies instead of using release tarballs.

### CODE REVIEW

**Comment by bigfootjon** [comment]
travis-ci shows pending, but if you click on it both builds passed

**Comment by yns88** [comment]
I believe I had the CI job do a composer update every time because occasionally a Hacklang update would break on previously locked versions of libraries, and I didn't want to manually upgrade them every time.

I guess the opposite is also a problem -- libraries can upgrade in a way that introduces type errors on an existing Hacklang version...

**Comment by bigfootjon** [comment]
I think it's better to require explicit upgrades. In theory CI runs should be reproducible. I guess that's not really the case anyway since we use `HHVM_VERISON=latest` but I think we should strive for it.

Perhaps dependabot could be configured to file PRs?

Otherwise I'm happy to revert that line

**Comment by yns88** [comment]
No, this is fine. If we want to split hairs, we could maybe do a composer update only when running on hhvm-latest, and use pinned deps when running on a pinned hhvm version, but even then I bet some edge cases would still break.

**Comment by fredemmott** [comment]
For what it's worth, the majority of projects under github.com/hhvm/ no longer commit composer.lock; I largely did that switch around a year ago when the rate of breaking changes was much higher. I was basically spending a day a week doing `composer update` diffs just to make Travis happy.

This should definitely be revisited when the language is more stable.

**Comment by fredemmott** [comment]
Ignoring vendor/*/tests: fyi the reason here is that GitHub's API is ratelimiting requests from TravisCI, and composer is falling back to doing a "git clone"

Composer does not support "don't checkout these files as a dependency", so all the dev-depends are also required to have a clean typechecker run. They're not in the release tarballs fetched via the API as github pays attention to the export-ignore gitattribute.

**Comment by bigfootjon** [comment]
@yns88 I feel like deleting ShipIt's `composer.lock` is the right call to bring things inline with other hhvm projects. Sound good to you?

**Comment by yns88** [comment]
Sounds good to me!

**Pull request closed without merging**
